"""empty message

Revision ID: 92ee7a98fdda
Revises: 22f074642985
Create Date: 2024-07-25 21:31:38.328816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ee7a98fdda'
down_revision = '22f074642985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_type', sa.String(), nullable=False),
    sa.Column('industry_name', sa.String(), nullable=False),
    sa.Column('Address', sa.String(), nullable=False),
    sa.Column('collection_point', sa.String(), nullable=False),
    sa.Column('contact_person', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(), nullable=False),
    sa.Column('rate', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('credit_date', sa.DateTime(), nullable=True),
    sa.Column('credit_amount', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_credits_package_id_packages')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credits_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produce', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('production_in_kilos', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('fk_produce_industry_id_industries')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_produce_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('active')

    op.drop_table('produce')
    op.drop_table('credits')
    op.drop_table('packages')
    op.drop_table('industries')
    # ### end Alembic commands ###
